export const FEAR_DATA = [
  {
    name: "Eye",
    id: "eye",
    color: "#39FF14",
    theme: "surveillance / knowledge",
    iconUrl: new URL("../assets/icons/fears/eye.svg", import.meta.url).href,
  },
  {
    name: "Web",
    id: "web",
    color: "#C6A300",
    theme: "manipulation / threads",
    iconUrl: new URL("../assets/icons/fears/web.svg", import.meta.url).href,
  },
  {
    name: "Spiral",
    id: "spiral",
    color: "#7A00FF",
    theme: "distortion / madness",
    iconUrl: new URL("../assets/icons/fears/spiral.svg", import.meta.url).href,
  },
  {
    name: "Buried",
    id: "buried",
    color: "#4B2E1F",
    theme: "pressure / underground",
    iconUrl: new URL("../assets/icons/fears/buried.svg", import.meta.url).href,
  },
  {
    name: "Vast",
    id: "vast",
    color: "#3A7BFF",
    theme: "height / endless space",
    iconUrl: new URL("../assets/icons/fears/vast.svg", import.meta.url).href,
  },
  {
    name: "Hunt",
    id: "hunt",
    color: "#FF8C00",
    theme: "predator / pursuit",
    iconUrl: new URL("../assets/icons/fears/hunt.svg", import.meta.url).href,
  },
  {
    name: "Slaughter",
    id: "slaughter",
    color: "#A80000",
    theme: "violence / war",
    iconUrl: new URL("../assets/icons/fears/slaughter.svg", import.meta.url).href,
  },
  {
    name: "Corruption",
    id: "corruption",
    color: "#6C8F00",
    theme: "infestation / corruption",
    iconUrl: new URL("../assets/icons/fears/corruption.svg", import.meta.url).href,
  },
  {
    name: "Flesh",
    id: "flesh",
    color: "#B03A48",
    theme: "body horror",
    iconUrl: new URL("../assets/icons/fears/flesh.svg", import.meta.url).href,
  },
  {
    name: "Dark",
    id: "dark",
    color: "#0D001A",
    theme: "blindness / unseen",
    iconUrl: new URL("../assets/icons/fears/dark.svg", import.meta.url).href,
  },
  {
    name: "Stranger",
    id: "stranger",
    color: "#CFCFCF",
    theme: "uncanny / masks",
    iconUrl: new URL("../assets/icons/fears/stranger.svg", import.meta.url).href,
  },
  {
    name: "End",
    id: "end",
    color: "#E8E3D9",
    theme: "death / inevitability",
    iconUrl: new URL("../assets/icons/fears/end.svg", import.meta.url).href,
  },
  {
    name: "Lonely",
    id: "lonely",
    color: "#6F87A8",
    theme: "isolation",
    iconUrl: new URL("../assets/icons/fears/lonely.svg", import.meta.url).href,
  },
  {
    name: "Desolation",
    id: "desolation",
    color: "#FF4500",
    theme: "fire / destruction",
    iconUrl: new URL("../assets/icons/fears/desolation.svg", import.meta.url).href,
  },
  {
    name: "Extinction",
    id: "extinction",
    color: "#7FFF00",
    theme: "apocalypse",
    iconUrl: new URL("../assets/icons/fears/extinction.svg", import.meta.url).href,
  },
];

export const FEAR_DATA_BY_ID = Object.fromEntries(FEAR_DATA.map((fear) => [fear.id, fear]));
